### ISSUE TITLE
Publish 1.4.2 to crates.io

### ISSUE THREAD

**Issue by Flaise** [zitsen/unqlite.rs#10]
The latest version of unqlite on crates.io is 1.4.1, which requires the concat_ident feature, which won't work on stable Rust. I configured a project to import v1.4.2 directly from the head of this repository and on cursory inspection, it seems work fine and appears ready for release. If there isn't a problem, could you publish 1.4.2? I'd much appreciate having all my dependencies archived in crates.io.

**Comment by zitsen** [comment]
sorry, auto release seems failed at my hand. publish done. thank you a lot for reporting this.
