### ISSUE TITLE
Failed to run custom build command for `unqlite v1.5.0`

### ISSUE THREAD

**Issue by RahulDas-dev** [zitsen/unqlite.rs#13]
Hi , 

I copy & paste the **Example code** provided in [readme  usage](https://github.com/rust-lang/rust-clippy#usage) section and then did `cargo run` . 

Found Following Error `error: failed to run custom build command for unqlite v1.5.0`

Screen Shot with `RUST_BACKTRACE=1`  
![unqlite_error](https://user-images.githubusercontent.com/32712591/147099878-0b6f5185-e250-4511-99e8-91cb01130af0.PNG)

Complete Error Log With `RUST_BACKTRACE=full`
[unqlite_error.txt](https://github.com/zitsen/unqlite.rs/files/7762833/unqlite_error.txt)

Rust Version  - `rustc 1.57.0 (f1edd0429 2021-11-29)`
Cargo Version - `cargo 1.57.0 (b2e52d7ca 2021-10-21)`
Operating System -`Windows, version 10.0.19042 X64`

I would greatly appreciate your assistance if I am missing something.

**Comment by zitsen** [comment]
The crate requires bindgen to automatically generate ffi bindings, that will require libclangAST.so or libcang.dll in your library path. See https://rust-lang.github.io/rust-bindgen/requirements.html#windows for bindgen documentations.
